[CmdletBinding()]
param([ValidateSet('fast','full','release')][string]$Mode='fast')
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$expectedPython='3.13.15'; $expectedDjango='5.2.17'; $expectedDrf='3.17.2'; $expectedPsycopg='3.2.13'; $expectedPostgres='16.15'; $baseline='django-api-2026.09'
Push-Location $root
try {
  function Assert-Command([string]$Name){if(-not(Get-Command $Name -ErrorAction SilentlyContinue)){throw "DEPENDENCY_BLOCKED: required command '$Name' is unavailable"}}
  function Invoke-Checked([string]$Label,[scriptblock]$Command){Write-Host "==> $Label"; & $Command; if($LASTEXITCODE -ne $null -and $LASTEXITCODE -ne 0){throw "${Label} failed with exit code $LASTEXITCODE"}}
  function Assert-Contains([string]$Text,[string]$Pattern,[string]$Failure){if($Text -notmatch $Pattern){throw $Failure}}

  Write-Host '==> STATIC_CONTRACT'
  foreach($file in @(
    'manage.py','requirements.txt','service-metadata.yml','Dockerfile','config/settings.py','config/asgi.py','config/observability.py','auth_health.py','config/urls.py','.env.local.example','scripts/certify_erp_client_platform.py','contracts/transversal-api.yml',
    'user/models.py','user/migrations/0006_application_scoped_email_identity.py','user/migrations/0007_drop_global_email_uniqueness.py','user/migrations/0008_case_insensitive_application_email.py','user/application_scope.py','user/account_scope.py','user/scoped_views.py','user/mobile_session_views.py','user/management/commands/audit_application_email_identity.py',
    'access/application_admin_scope.py','access/scoped_admin_views.py','access/test_application_scoped_rbac.py','access/test_application_admin_scope.py','access/global_identity.py','access/global_identity_models.py','access/migrations/0039_global_identity_correlation.py','access/migrations/0041_merge_global_identity_and_permission_seeds.py',
    'auth/custom_email.py','auth/tests/test_trusted_application_context.py','auth/tests/test_application_scoped_identity_flows.py','auth/tests/test_application_email_identity_preflight.py','auth/tests/test_application_email_identity_constraint.py','auth/tests/test_application_scoped_refresh.py','auth/tests/test_application_scoped_session_revocation.py','auth/tests/test_application_scoped_password_change.py','auth/tests/test_application_scoped_password_reset_confirm.py','auth/tests/test_email_trusted_application_context.py','auth/tests/test_application_email_template_fallback.py','auth/tests/test_email_sender_fallback_contract.py','auth/tests/test_email_branding_fallback_contract.py','auth/tests/test_global_identity_contract.py'
  )){if(-not(Test-Path -LiteralPath $file)){throw "STATIC_CONTRACT_FAILURE: missing required file $file"}}

  $metadata=Get-Content service-metadata.yml -Raw; $transversal=Get-Content contracts/transversal-api.yml -Raw
  foreach($token in @('contract: transversal_http','health: /health/','readiness: /ready/','request_id_header: X-Request-ID','correlation_id_header: X-Correlation-ID','BUSINESS_TRAFFIC_GATEWAY_ONLY')){if($transversal -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: transversal contract missing $token"}}
  foreach($pattern in @('framework_policy_version:\s*["'']2026\.09\.3["'']','api_platform_baseline:\s*["'']django-api-2026\.09["'']','api_platform_adoption_state:\s*CANDIDATE','python:\s*["'']3\.13\.15["'']','django:\s*["'']5\.2\.17["'']','drf:\s*["'']3\.17\.2["'']','engine:\s*postgresql','deploy_authority_branch:\s*pro','user_policy:\s*DB_USER_EQUALS_DB_NAME','readiness_path:\s*/ready/','command:\s*scripts/ci/local-validate\.ps1')){Assert-Contains $metadata $pattern "STATIC_CONTRACT_FAILURE: service metadata baseline mismatch ($pattern)"}
  $requirements=Get-Content requirements.txt -Raw; foreach($token in @('Django==5.2.17','djangorestframework==3.17.2','psycopg[binary]==3.2.13')){if($requirements -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: requirements target missing $token"}}
  $dockerfile=Get-Content Dockerfile -Raw; Assert-Contains $dockerfile 'FROM\s+python:3\.13\.15-slim-bookworm' 'STATIC_CONTRACT_FAILURE: Docker Python target missing'; if($dockerfile -match 'python -m pip install -r requirements\.txt\s+"uvicorn'){throw 'STATIC_CONTRACT_FAILURE: Uvicorn must come from requirements.txt'}
  $certifier=Get-Content scripts/certify_erp_client_platform.py -Raw; if($certifier -match 'PostgreSQL 14\.4|140004'){throw 'STATIC_CONTRACT_FAILURE: legacy PostgreSQL target remains'}; if($certifier -notmatch 'PostgreSQL 16\.15' -or $certifier -notmatch '160015'){throw 'STATIC_CONTRACT_FAILURE: PostgreSQL 16.15 target missing'}
  $settings=Get-Content config/settings.py -Raw; if($settings -match 'django\.db\.backends\.sqlite3'){throw 'STATIC_CONTRACT_FAILURE: SQLite prohibited'}; if($settings -notmatch 'django\.db\.backends\.postgresql'){throw 'STATIC_CONTRACT_FAILURE: PostgreSQL must be explicit'}; if($settings -notmatch 'search_path=\{search_path\}' -or $settings -notmatch '_append_search_path\(options,[\s\S]*?AuthRuntime",public'){throw 'STATIC_CONTRACT_FAILURE: PostgreSQL search_path must include public'}; if($settings -notmatch 'DB_USER == DB_NAME' -and $settings -notmatch 'config\.get\("NAME"\) != config\.get\("USER"\)'){throw 'STATIC_CONTRACT_FAILURE: DB_USER == DB_NAME enforcement missing'}; if($settings -notmatch 'GATEWAY_INTERNAL_SHARED_SECRET\s*=\s*getenv\("GATEWAY_INTERNAL_SHARED_SECRET"'){throw 'STATIC_CONTRACT_FAILURE: Gateway secret setting missing'}

  $scope=Get-Content user/application_scope.py -Raw; foreach($token in @('X-Application-Code','X-Gateway-Internal-Token','APPLICATION_CONTEXT_MISMATCH','GATEWAY_CONTEXT_REQUIRED','APPLICATION_CODE_REQUIRED')){if($scope -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: trusted context missing $token"}}
  $account=Get-Content user/account_scope.py -Raw; foreach($token in @('def normalize_email','def find_local_account','email__iexact','idApp=application.ApplicationID')){if($account -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: account scope missing $token"}}
  $views=Get-Content user/scoped_views.py -Raw; foreach($token in @('ApplicationScopedTokenObtainPairView','ApplicationScopedUserViewSet','identity.password.reset.requested','APPLICATION_ACCESS_DENIED')){if($views -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: scoped identity flow missing $token"}}
  $admin=Get-Content access/application_admin_scope.py -Raw; foreach($token in @('resolve_admin_target_application','is_superuser','Delegated administrators')){if($admin -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: admin scope missing $token"}}
  $scopedRbac=Get-Content access/scoped_rbac_views.py -Raw; if($scopedRbac -notmatch [regex]::Escape('ApplicationScopedMePermissionsViewSet')){throw 'STATIC_CONTRACT_FAILURE: scoped me-permissions view missing'}; $scopedAdmin=Get-Content access/scoped_admin_views.py -Raw; foreach($token in @('ApplicationScopedIdentityUserViewSet','ApplicationScopedRoleViewSet','ApplicationScopedPermissionViewSet')){if($scopedAdmin -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: scoped admin view missing $token"}}
  $preflight=Get-Content user/management/commands/audit_application_email_identity.py -Raw; foreach($token in @('Lower("email")','duplicate_application_email_groups','orphan_application_ids','safe_for_application_email_constraint')){if($preflight -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: identity preflight missing $token"}}
  $userModel=Get-Content user/models.py -Raw; if($userModel -match 'email\s*=\s*models\.EmailField\([^\r\n]*unique=True'){throw 'STATIC_CONTRACT_FAILURE: Task 5 forbids global email uniqueness'}; foreach($token in @('UniqueConstraint','models.F("idApp")','Lower("email")','uq_useraccounts_application_email')){if($userModel -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: Task 5 case-insensitive application email contract missing $token"}}
  $authViews=Get-Content user/views.py -Raw; if($authViews -notmatch 'validate_password\(new_password,\s*user=request\.user\)'){throw 'STATIC_CONTRACT_FAILURE: required password change must use centralized password validators'}; if($authViews -match 'class LogoutView\s*\('){throw 'STATIC_CONTRACT_FAILURE: duplicate noncanonical LogoutView remains in user/views.py'}
  $globalIdentity=Get-Content access/global_identity.py -Raw; foreach($token in @('APPLICATION_ACCOUNT_MISMATCH','GLOBAL_IDENTITY_ACCOUNT_ALREADY_LINKED','global_identity.link.requested','global_identity.unlinked')){if($globalIdentity -notmatch [regex]::Escape($token)){throw "STATIC_CONTRACT_FAILURE: Task 8 global identity contract missing $token"}}

  $envText=Get-Content '.env.local.example' -Raw; if($envText -notmatch '(?m)^AUTH_DB_NAME=Auth\s*$' -or $envText -notmatch '(?m)^AUTH_DB_USER=Auth\s*$'){throw 'STATIC_CONTRACT_FAILURE: canonical Auth DB identity missing'}; if($envText -notmatch '(?m)^GATEWAY_INTERNAL_SHARED_SECRET=\s*$'){throw 'STATIC_CONTRACT_FAILURE: Gateway env contract missing'}; if($envText -match '(?im)^\w*(DB_USER|POSTGRES_USER)=.*_user\s*$'){throw 'STATIC_CONTRACT_FAILURE: legacy DB alias detected'}; if($envText -match '(?i)(change-me|replace-me|replace_with_|dev-[a-z0-9-]*secret|local-[a-z0-9-]*secret)'){throw 'STATIC_CONTRACT_FAILURE: predictable placeholder secret detected'}
  $urls=Get-Content config/urls.py -Raw; $health=Get-Content auth_health.py -Raw; if($urls -notmatch 'path\("health/"' -or $urls -notmatch 'path\("ready/"'){throw 'STATIC_CONTRACT_FAILURE: health/readiness routes required'}; if($urls -notmatch 'ApplicationScopedUserViewSet'){throw 'STATIC_CONTRACT_FAILURE: identity routes not application scoped'}; foreach($route in @('activation/','resend_activation/','reset_password/','reset_password_confirm/','set_email/','reset_email/','reset_email_confirm/')){if($urls -notmatch [regex]::Escape($route)){throw "STATIC_CONTRACT_FAILURE: scoped route missing $route"}}; if($health -notmatch 'connection\.ensure_connection\(\)' -or $health -notmatch 'status=503'){throw 'STATIC_CONTRACT_FAILURE: readiness DB verification missing'}
  $asgi=Get-Content config/asgi.py -Raw; $obs=Get-Content config/observability.py -Raw; if($asgi -notmatch 'ObservabilityMiddleware\(get_asgi_application\(\)\)'){throw 'STATIC_CONTRACT_FAILURE: ASGI observability wrapper required'}; if($obs -notmatch 'x-request-id' -or $obs -notmatch 'x-correlation-id' -or $obs -notmatch 'json\.dumps'){throw 'STATIC_CONTRACT_FAILURE: request/correlation JSON observability missing'}
  if(Test-Path '.github/workflows'){foreach($workflow in Get-ChildItem '.github/workflows' -File | Where-Object Extension -in @('.yml','.yaml')){$text=Get-Content $workflow.FullName -Raw; if($text -match '(?m)^\s*(push|pull_request|pull_request_target|merge_group|schedule|workflow_run|repository_dispatch):' -or $text -match '(?m)^\s*on:\s*\[[^\]]*(push|pull_request|schedule|workflow_run|repository_dispatch)'){throw "STATIC_CONTRACT_FAILURE: hosted workflow $($workflow.Name) has forbidden trigger"}; if($text -notmatch 'workflow_dispatch'){throw "STATIC_CONTRACT_FAILURE: hosted workflow $($workflow.Name) not manual"}; if($text -notmatch 'refs/heads/pro'){throw "STATIC_CONTRACT_FAILURE: hosted workflow $($workflow.Name) not restricted to pro"}}}

  Assert-Command git; Invoke-Checked 'STATIC_CONTRACT git diff --check' {git diff --check}
  Assert-Command python; $pythonVersion=(& python -c 'import platform; print(platform.python_version())').Trim(); if($LASTEXITCODE -ne 0){throw 'DEPENDENCY_BLOCKED: unable to inspect Python runtime'}; if($pythonVersion -ne $expectedPython){throw "DEPENDENCY_BLOCKED: Python $expectedPython required; found $pythonVersion"}
  Write-Host '==> PYTHON_COMPILE'; Invoke-Checked 'PYTHON_COMPILE' {python -m compileall -q . -x '(^|/)(\.git|\.venv|venv|node_modules)/'}

  if($Mode -in @('full','release')){
    Invoke-Checked 'pip dependency check' {python -m pip check}; Invoke-Checked 'installed framework tuple' {python -c "import django,rest_framework,psycopg; assert django.get_version() == '$expectedDjango'; assert rest_framework.VERSION == '$expectedDrf'; assert psycopg.__version__ == '$expectedPsycopg'"}
    Write-Host '==> DJANGO_CHECK'; Invoke-Checked 'DJANGO_CHECK' {python manage.py check}; Invoke-Checked 'Django deploy check' {python manage.py check --deploy}
    Write-Host '==> MIGRATION_CHECK'; Invoke-Checked 'MIGRATION_CHECK drift' {python manage.py makemigrations --check --dry-run}; Invoke-Checked 'MIGRATION_CHECK plan' {python manage.py migrate --plan}
    Write-Host '==> FOCUSED_TESTS'; Invoke-Checked 'Task 3 scoped identity tests' {python manage.py test auth.tests.test_application_scoped_identity_flows -v 2 --keepdb}; Invoke-Checked 'Task 4 scoped RBAC/admin tests' {python manage.py test access.test_application_scoped_rbac access.test_application_admin_scope -v 2 --keepdb}; Invoke-Checked 'Task 5 identity preflight and PostgreSQL constraint tests' {python manage.py test auth.tests.test_application_email_identity_preflight auth.tests.test_application_email_identity_constraint -v 2 --keepdb}; Invoke-Checked 'Task 5 live identity preflight' {python manage.py audit_application_email_identity --json}; Invoke-Checked 'Task 6 application-scoped session/password tests' {python manage.py test auth.tests.test_application_scoped_refresh auth.tests.test_application_scoped_session_revocation auth.tests.test_application_scoped_password_change auth.tests.test_application_scoped_password_reset_confirm -v 2 --keepdb}; Invoke-Checked 'Task 7 multi-application email tests' {python manage.py test auth.tests.test_email_trusted_application_context auth.tests.test_application_email_template_fallback auth.tests.test_email_sender_fallback_contract auth.tests.test_email_branding_fallback_contract -v 2 --keepdb}; Invoke-Checked 'Task 8 global identity tests' {python manage.py test auth.tests.test_global_identity_contract -v 2 --keepdb}
    Write-Host '==> FULL_TESTS'; Invoke-Checked 'FULL_TESTS' {python manage.py test -v 2 --keepdb}
    Write-Host '==> POSTGRES_OWNER_CERTIFICATION'; Invoke-Checked 'POSTGRES_OWNER_CERTIFICATION' {python scripts/certify_erp_client_platform.py}
  }
  if($Mode -eq 'release'){
    foreach($tool in @('docker','trivy','syft')){Assert-Command $tool}; $tag="local/auth-release-check:$([DateTimeOffset]::UtcNow.ToUnixTimeSeconds())"; $sbom=Join-Path $env:TEMP "auth-sbom-$([guid]::NewGuid().ToString('N')).json"
    try{Invoke-Checked 'Docker build' {docker build --pull --file Dockerfile --tag $tag .}; Invoke-Checked 'container version tuple' {docker run --rm --entrypoint python $tag -c "import platform,django,rest_framework,psycopg; assert platform.python_version() == '$expectedPython'; assert django.get_version() == '$expectedDjango'; assert rest_framework.VERSION == '$expectedDrf'; assert psycopg.__version__ == '$expectedPsycopg'"}; Invoke-Checked 'Trivy vulnerability and secret scan' {trivy image --exit-code 1 --severity CRITICAL --scanners vuln,secret --ignore-unfixed $tag}; Invoke-Checked 'SBOM generation' {syft $tag -o cyclonedx-json=$sbom}; if(-not(Test-Path $sbom)){throw 'RUNTIME_VERIFICATION_REQUIRED: SBOM not generated'}} finally{Remove-Item $sbom -Force -ErrorAction SilentlyContinue; docker image rm $tag 2>$null | Out-Null}
  }
  [pscustomobject]@{Status='PASS';Mode=$Mode;StaticContract='PASS';Runtime=if($Mode -eq 'fast'){'RUNTIME_VERIFICATION_REQUIRED'}else{'OBSERVED_BY_THIS_RUN'};FrameworkPolicy='2026.09.3';ApiPlatformBaseline=$baseline;Python=$expectedPython;Django=$expectedDjango;DRF=$expectedDrf;Psycopg=$expectedPsycopg;PostgreSQLTarget=$expectedPostgres;Repository='MexIngSof/API.PY.DJANGO.Auth'}
} finally {Pop-Location}
