# Generated by Django 4.2.5 on 2026-05-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "RoleID",
                    models.AutoField(
                        db_column="RoleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Name",
                    models.CharField(db_column="Name", max_length=100, unique=True),
                ),
                (
                    "Description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Roles",
            },
        ),
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "RoleID",
                    models.ForeignKey(
                        db_column="RoleID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.roles",
                    ),
                ),
            ],
            options={
                "db_table": "UserRoles",
            },
        ),
    ]
