# Generated by Django 4.2.5 on 2026-05-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        ("user", "0002_auth_schema_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userroles",
            name="UserID",
            field=models.ForeignKey(
                db_column="UserID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroles",
            unique_together={("UserID", "RoleID")},
        ),
    ]
