# Generated by Django 4.2.5 on 2026-05-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
        ("user", "0002_auth_schema_table"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'Auth'
                      AND table_name = 'UserAccounts'
                      AND column_name = 'id'
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'Auth'
                      AND table_name = 'UserAccounts'
                      AND column_name = 'Id'
                ) THEN
                    ALTER TABLE "Auth"."UserAccounts" RENAME COLUMN id TO "Id";
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="userroles",
            name="UserID",
            field=models.ForeignKey(
                db_column="UserID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroles",
            unique_together={("UserID", "RoleID")},
        ),
    ]
