# Generated by Django 4.2.30 on 2026-05-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roles", "0003_auth_schema_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="RoleID",
            field=models.AutoField(db_column="Id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userroles",
            name="RoleID",
            field=models.ForeignKey(
                db_column="RoleId",
                on_delete=django.db.models.deletion.CASCADE,
                to="roles.roles",
            ),
        ),
        migrations.AlterField(
            model_name="userroles",
            name="UserID",
            field=models.ForeignKey(
                db_column="UserId",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
