# Generated by Django 4.2.30 on 2026-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0004_alter_roles_roleid_alter_userroles_roleid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userroles",
            name="id",
            field=models.BigAutoField(
                db_column="Id", primary_key=True, serialize=False
            ),
        ),
    ]
