# Generated by Django 4.2.26 on 2026-10-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0004_useraccount_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountGroup',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('useraccount', models.ForeignKey(db_column='UserAccountId', on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
                ('group', models.ForeignKey(db_column='GroupId', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'user_useraccount_groups',
                'managed': False,
                'unique_together': {('useraccount', 'group')},
            },
        ),
        migrations.CreateModel(
            name='UserAccountUserPermission',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('useraccount', models.ForeignKey(db_column='UserAccountId', on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
                ('permission', models.ForeignKey(db_column='PermissionId', on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'db_table': 'user_useraccount_user_permissions',
                'managed': False,
                'unique_together': {('useraccount', 'permission')},
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "id" TO "Id"',
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "useraccount_id" TO "UserAccountId"',
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "group_id" TO "GroupId"',
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "id" TO "Id"',
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "useraccount_id" TO "UserAccountId"',
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "permission_id" TO "PermissionId"',
            ],
            reverse_sql=[
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "PermissionId" TO "permission_id"',
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "UserAccountId" TO "useraccount_id"',
                'ALTER TABLE "Auth"."user_useraccount_user_permissions" RENAME COLUMN "Id" TO "id"',
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "GroupId" TO "group_id"',
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "UserAccountId" TO "useraccount_id"',
                'ALTER TABLE "Auth"."user_useraccount_groups" RENAME COLUMN "Id" TO "id"',
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='useraccount',
                    name='groups',
                    field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', through='user.UserAccountGroup', through_fields=('useraccount', 'group'), to='auth.group', verbose_name='groups'),
                ),
                migrations.AlterField(
                    model_name='useraccount',
                    name='user_permissions',
                    field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', through='user.UserAccountUserPermission', through_fields=('useraccount', 'permission'), to='auth.permission', verbose_name='user permissions'),
                ),
            ],
        ),
    ]
