# Generated by Django 5.2.17 on 2026-10-07 07:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0007_drop_global_email_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraccount',
            name='uq_useraccounts_application_email',
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(models.F('idApp'), django.db.models.functions.text.Lower('email'), name='uq_useraccounts_application_email'),
        ),
    ]
