# Generated by Django 4.2.5 on 2026-05-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "ActionID",
                    models.AutoField(
                        db_column="ActionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Name",
                    models.CharField(db_column="Name", max_length=50, unique=True),
                ),
                (
                    "Description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Actions",
            },
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "ModuleID",
                    models.AutoField(
                        db_column="ModuleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Name",
                    models.CharField(db_column="Name", max_length=100, unique=True),
                ),
                (
                    "Description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "Code",
                    models.CharField(db_column="Code", max_length=100, unique=True),
                ),
                ("Path", models.CharField(db_column="Path", max_length=255)),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Modules",
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "PermissionID",
                    models.AutoField(
                        db_column="PermissionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Code",
                    models.CharField(db_column="Code", max_length=150, unique=True),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Permissions",
            },
        ),
        migrations.CreateModel(
            name="RolePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "RolePermissions",
            },
        ),
        migrations.CreateModel(
            name="UserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Allow", models.BooleanField(db_column="Allow", default=True)),
                (
                    "Reason",
                    models.CharField(
                        blank=True, db_column="Reason", max_length=255, null=True
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "PermissionID",
                    models.ForeignKey(
                        db_column="PermissionID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.permissions",
                    ),
                ),
            ],
            options={
                "db_table": "UserPermissions",
            },
        ),
    ]
