# Generated by Django 4.2.5 on 2026-05-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("roles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissions",
            name="UserID",
            field=models.ForeignKey(
                db_column="UserID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolepermissions",
            name="PermissionID",
            field=models.ForeignKey(
                db_column="PermissionID",
                on_delete=django.db.models.deletion.CASCADE,
                to="access.permissions",
            ),
        ),
        migrations.AddField(
            model_name="rolepermissions",
            name="RoleID",
            field=models.ForeignKey(
                db_column="RoleID",
                on_delete=django.db.models.deletion.CASCADE,
                to="roles.roles",
            ),
        ),
        migrations.AddField(
            model_name="permissions",
            name="ActionID",
            field=models.ForeignKey(
                db_column="ActionID",
                on_delete=django.db.models.deletion.CASCADE,
                to="access.actions",
            ),
        ),
        migrations.AddField(
            model_name="permissions",
            name="ModuleID",
            field=models.ForeignKey(
                db_column="ModuleID",
                on_delete=django.db.models.deletion.CASCADE,
                to="access.modules",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermissions",
            unique_together={("UserID", "PermissionID")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermissions",
            unique_together={("RoleID", "PermissionID")},
        ),
    ]
