# Generated by Django 4.2.5 on 2026-05-11 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roles", "0003_auth_schema_tables"),
        ("access", "0003_auth_schema_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "ApplicationID",
                    models.AutoField(
                        db_column="ApplicationID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Code",
                    models.CharField(db_column="Code", max_length=50, unique=True),
                ),
                ("Name", models.CharField(db_column="Name", max_length=100)),
                (
                    "Description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": '"Auth"."Applications"',
            },
        ),
        migrations.CreateModel(
            name="UserDevices",
            fields=[
                (
                    "DeviceID",
                    models.BigAutoField(
                        db_column="DeviceID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "DeviceName",
                    models.CharField(
                        blank=True, db_column="DeviceName", max_length=150
                    ),
                ),
                (
                    "DeviceType",
                    models.CharField(blank=True, db_column="DeviceType", max_length=50),
                ),
                (
                    "OperatingSystem",
                    models.CharField(
                        blank=True, db_column="OperatingSystem", max_length=100
                    ),
                ),
                (
                    "Browser",
                    models.CharField(blank=True, db_column="Browser", max_length=100),
                ),
                (
                    "IpAddress",
                    models.GenericIPAddressField(
                        blank=True, db_column="IpAddress", null=True
                    ),
                ),
                ("UserAgent", models.TextField(blank=True, db_column="UserAgent")),
                (
                    "FingerprintHash",
                    models.CharField(db_column="FingerprintHash", max_length=128),
                ),
                (
                    "IsTrusted",
                    models.BooleanField(db_column="IsTrusted", default=False),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "LastSeenAt",
                    models.DateTimeField(auto_now=True, db_column="LastSeenAt"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "RevokedAt",
                    models.DateTimeField(blank=True, db_column="RevokedAt", null=True),
                ),
                (
                    "RevokedReason",
                    models.CharField(
                        blank=True, db_column="RevokedReason", max_length=255
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."UserDevices"',
                "unique_together": {("UserID", "FingerprintHash")},
            },
        ),
        migrations.CreateModel(
            name="UserSessions",
            fields=[
                (
                    "SessionID",
                    models.BigAutoField(
                        db_column="SessionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "AccessTokenJti",
                    models.CharField(
                        blank=True, db_column="AccessTokenJti", max_length=255
                    ),
                ),
                (
                    "RefreshTokenHash",
                    models.CharField(
                        blank=True, db_column="RefreshTokenHash", max_length=128
                    ),
                ),
                (
                    "StartedAt",
                    models.DateTimeField(auto_now_add=True, db_column="StartedAt"),
                ),
                (
                    "LastActivityAt",
                    models.DateTimeField(auto_now=True, db_column="LastActivityAt"),
                ),
                (
                    "ExpiresAt",
                    models.DateTimeField(blank=True, db_column="ExpiresAt", null=True),
                ),
                (
                    "RevokedAt",
                    models.DateTimeField(blank=True, db_column="RevokedAt", null=True),
                ),
                (
                    "RevokedReason",
                    models.CharField(
                        blank=True, db_column="RevokedReason", max_length=255
                    ),
                ),
                ("IsOnline", models.BooleanField(db_column="IsOnline", default=True)),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApplicationID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.applications",
                    ),
                ),
                (
                    "DeviceID",
                    models.ForeignKey(
                        blank=True,
                        db_column="DeviceID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.userdevices",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."UserSessions"',
            },
        ),
        migrations.CreateModel(
            name="RefreshTokens",
            fields=[
                (
                    "RefreshTokenID",
                    models.BigAutoField(
                        db_column="RefreshTokenID", primary_key=True, serialize=False
                    ),
                ),
                ("TokenHash", models.CharField(db_column="TokenHash", max_length=128)),
                ("Jti", models.CharField(blank=True, db_column="Jti", max_length=255)),
                (
                    "ExpiresAt",
                    models.DateTimeField(blank=True, db_column="ExpiresAt", null=True),
                ),
                (
                    "RevokedAt",
                    models.DateTimeField(blank=True, db_column="RevokedAt", null=True),
                ),
                (
                    "RevokedReason",
                    models.CharField(
                        blank=True, db_column="RevokedReason", max_length=255
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "SessionID",
                    models.ForeignKey(
                        blank=True,
                        db_column="SessionID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.usersessions",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."RefreshTokens"',
            },
        ),
        migrations.CreateModel(
            name="RecoveryCodes",
            fields=[
                (
                    "RecoveryCodeID",
                    models.BigAutoField(
                        db_column="RecoveryCodeID", primary_key=True, serialize=False
                    ),
                ),
                ("CodeHash", models.CharField(db_column="CodeHash", max_length=255)),
                (
                    "UsedAt",
                    models.DateTimeField(blank=True, db_column="UsedAt", null=True),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."RecoveryCodes"',
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "PasswordHistoryID",
                    models.BigAutoField(
                        db_column="PasswordHistoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "PasswordHash",
                    models.CharField(db_column="PasswordHash", max_length=255),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."PasswordHistory"',
            },
        ),
        migrations.CreateModel(
            name="MfaMethods",
            fields=[
                (
                    "MfaMethodID",
                    models.BigAutoField(
                        db_column="MfaMethodID", primary_key=True, serialize=False
                    ),
                ),
                ("MethodType", models.CharField(db_column="MethodType", max_length=50)),
                (
                    "SecretHash",
                    models.CharField(
                        blank=True, db_column="SecretHash", max_length=255
                    ),
                ),
                (
                    "IsEnabled",
                    models.BooleanField(db_column="IsEnabled", default=False),
                ),
                (
                    "VerifiedAt",
                    models.DateTimeField(blank=True, db_column="VerifiedAt", null=True),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."MfaMethods"',
            },
        ),
        migrations.CreateModel(
            name="LoginAttempts",
            fields=[
                (
                    "LoginAttemptID",
                    models.BigAutoField(
                        db_column="LoginAttemptID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "Email",
                    models.EmailField(blank=True, db_column="Email", max_length=255),
                ),
                (
                    "ApplicationCode",
                    models.CharField(
                        blank=True, db_column="ApplicationCode", max_length=50
                    ),
                ),
                (
                    "IpAddress",
                    models.GenericIPAddressField(
                        blank=True, db_column="IpAddress", null=True
                    ),
                ),
                ("UserAgent", models.TextField(blank=True, db_column="UserAgent")),
                ("Success", models.BooleanField(db_column="Success", default=False)),
                (
                    "FailureReason",
                    models.CharField(
                        blank=True, db_column="FailureReason", max_length=255
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."LoginAttempts"',
            },
        ),
        migrations.CreateModel(
            name="AccessAuditEvents",
            fields=[
                (
                    "AccessAuditEventID",
                    models.BigAutoField(
                        db_column="AccessAuditEventID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("EventType", models.CharField(db_column="EventType", max_length=100)),
                (
                    "IpAddress",
                    models.GenericIPAddressField(
                        blank=True, db_column="IpAddress", null=True
                    ),
                ),
                ("UserAgent", models.TextField(blank=True, db_column="UserAgent")),
                (
                    "Metadata",
                    models.JSONField(blank=True, db_column="Metadata", default=dict),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApplicationID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.applications",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."AccessAuditEvents"',
            },
        ),
        migrations.CreateModel(
            name="ApplicationRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        db_column="ApplicationID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.applications",
                    ),
                ),
                (
                    "RoleID",
                    models.ForeignKey(
                        db_column="RoleID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roles.roles",
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."ApplicationRoles"',
                "unique_together": {("ApplicationID", "RoleID")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        db_column="ApplicationID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.applications",
                    ),
                ),
                (
                    "PermissionID",
                    models.ForeignKey(
                        db_column="PermissionID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.permissions",
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."ApplicationPermissions"',
                "unique_together": {("ApplicationID", "PermissionID")},
            },
        ),
    ]
