# Generated by Django 4.2.30 on 2026-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0006_alter_accessauditevents_accessauditeventid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationpermissions",
            name="id",
            field=models.BigAutoField(
                db_column="Id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="applicationroles",
            name="id",
            field=models.BigAutoField(
                db_column="Id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rolepermissions",
            name="id",
            field=models.BigAutoField(
                db_column="Id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userpermissions",
            name="id",
            field=models.BigAutoField(
                db_column="Id", primary_key=True, serialize=False
            ),
        ),
    ]
