# Generated by Django 4.2.30 on 2026-05-11 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0007_alter_applicationpermissions_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialProviders",
            fields=[
                (
                    "SocialProviderID",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "Code",
                    models.CharField(db_column="Code", max_length=50, unique=True),
                ),
                ("Name", models.CharField(db_column="Name", max_length=100)),
                (
                    "BackendName",
                    models.CharField(
                        db_column="BackendName", max_length=100, unique=True
                    ),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": '"Auth"."SocialProviders"',
            },
        ),
        migrations.CreateModel(
            name="SocialLoginAttempts",
            fields=[
                (
                    "SocialLoginAttemptID",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ApplicationCode",
                    models.CharField(
                        blank=True, db_column="ApplicationCode", max_length=50
                    ),
                ),
                (
                    "Email",
                    models.EmailField(blank=True, db_column="Email", max_length=255),
                ),
                (
                    "IpAddress",
                    models.GenericIPAddressField(
                        blank=True, db_column="IpAddress", null=True
                    ),
                ),
                ("UserAgent", models.TextField(blank=True, db_column="UserAgent")),
                ("Success", models.BooleanField(db_column="Success", default=False)),
                (
                    "FailureReason",
                    models.CharField(
                        blank=True, db_column="FailureReason", max_length=255
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "SocialProviderID",
                    models.ForeignKey(
                        blank=True,
                        db_column="SocialProviderId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.socialproviders",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."SocialLoginAttempts"',
            },
        ),
        migrations.CreateModel(
            name="UserSocialAccounts",
            fields=[
                (
                    "UserSocialAccountID",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ProviderUserId",
                    models.CharField(db_column="ProviderUserId", max_length=255),
                ),
                (
                    "Email",
                    models.EmailField(blank=True, db_column="Email", max_length=255),
                ),
                (
                    "DisplayName",
                    models.CharField(
                        blank=True, db_column="DisplayName", max_length=255
                    ),
                ),
                (
                    "ProfileUrl",
                    models.URLField(blank=True, db_column="ProfileUrl", max_length=500),
                ),
                (
                    "AvatarUrl",
                    models.URLField(blank=True, db_column="AvatarUrl", max_length=500),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "LastLoginAt",
                    models.DateTimeField(
                        blank=True, db_column="LastLoginAt", null=True
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "SocialProviderID",
                    models.ForeignKey(
                        db_column="SocialProviderId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.socialproviders",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        db_column="UserId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."UserSocialAccounts"',
                "unique_together": {("SocialProviderID", "ProviderUserId")},
            },
        ),
    ]
