# Generated by Django 4.2.30 on 2026-05-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0009_seed_social_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionalEmailTemplates",
            fields=[
                (
                    "TransactionalEmailTemplateID",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                ("ActionCode", models.CharField(db_column="ActionCode", max_length=80)),
                (
                    "LanguageCode",
                    models.CharField(
                        db_column="LanguageCode", default="es-MX", max_length=10
                    ),
                ),
                (
                    "Channel",
                    models.CharField(
                        db_column="Channel", default="EMAIL", max_length=30
                    ),
                ),
                ("SubjectTemplate", models.TextField(db_column="SubjectTemplate")),
                (
                    "TextBodyTemplate",
                    models.TextField(blank=True, db_column="TextBodyTemplate"),
                ),
                (
                    "HtmlBodyTemplate",
                    models.TextField(blank=True, db_column="HtmlBodyTemplate"),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        db_column="ApplicationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.applications",
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."TransactionalEmailTemplates"',
                "unique_together": {
                    ("ApplicationID", "ActionCode", "LanguageCode", "Channel")
                },
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryLogs",
            fields=[
                (
                    "EmailDeliveryLogID",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                ("ActionCode", models.CharField(db_column="ActionCode", max_length=80)),
                ("ToEmail", models.EmailField(db_column="ToEmail", max_length=255)),
                (
                    "Subject",
                    models.CharField(blank=True, db_column="Subject", max_length=255),
                ),
                (
                    "Status",
                    models.CharField(
                        db_column="Status", default="CREATED", max_length=40
                    ),
                ),
                (
                    "ErrorMessage",
                    models.TextField(blank=True, db_column="ErrorMessage"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "SentAt",
                    models.DateTimeField(blank=True, db_column="SentAt", null=True),
                ),
                (
                    "ApplicationID",
                    models.ForeignKey(
                        blank=True,
                        db_column="ApplicationId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.applications",
                    ),
                ),
                (
                    "TransactionalEmailTemplateID",
                    models.ForeignKey(
                        blank=True,
                        db_column="TransactionalEmailTemplateId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.transactionalemailtemplates",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."EmailDeliveryLogs"',
            },
        ),
        migrations.CreateModel(
            name="ApplicationEmailSettings",
            fields=[
                (
                    "ApplicationEmailSettingID",
                    models.BigAutoField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "CommercialName",
                    models.CharField(db_column="CommercialName", max_length=150),
                ),
                (
                    "LogoUrl",
                    models.URLField(blank=True, db_column="LogoUrl", max_length=500),
                ),
                (
                    "PrimaryColor",
                    models.CharField(
                        blank=True, db_column="PrimaryColor", max_length=20
                    ),
                ),
                (
                    "SenderEmail",
                    models.EmailField(db_column="SenderEmail", max_length=255),
                ),
                (
                    "SenderName",
                    models.CharField(db_column="SenderName", max_length=150),
                ),
                (
                    "BaseDomain",
                    models.CharField(
                        blank=True, db_column="BaseDomain", max_length=255
                    ),
                ),
                (
                    "RedirectBaseUrl",
                    models.URLField(
                        blank=True, db_column="RedirectBaseUrl", max_length=500
                    ),
                ),
                ("IsActive", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "UpdatedAt",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "ApplicationID",
                    models.OneToOneField(
                        db_column="ApplicationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.applications",
                    ),
                ),
            ],
            options={
                "db_table": '"Auth"."ApplicationEmailSettings"',
            },
        ),
    ]
